In [ ]:
#importing the new translated dataset

In [1]:
import pandas as pd

new_df = pd.read_excel("/content/propaganda_translator_datasheet.xlsx")

new_df["propaganda_label"] = new_df["propaganda_label"].map({
    -1: 0,
     1: 1
})

In [2]:
new_df.shape

(3978, 7)

In [3]:
new_df = new_df[["article_text_en", "propaganda_label"]]

new_df = new_df.rename(columns={
    "article_text_en": "text",
    "propaganda_label": "label"
})

In [4]:
new_df.to_csv("new_dataset_clean.csv", index=False)

In [5]:
old_df = pd.read_csv("/content/propaganda_dataset_for_bert.csv") #importing old dataset

In [6]:
old_df = old_df[["text","label"]]

In [7]:
combined_df = pd.concat([old_df, new_df], ignore_index=True) #merging the datasets

In [8]:
combined_df = combined_df.sample(frac=1, random_state=42)  #shuffling

In [9]:
 combined_df.to_csv("combined_dataset.csv", index=False)  #saving the combined csv

PREPROCESSING + EDA

In [10]:
df = pd.read_csv("combined_dataset.csv")

In [11]:
df.shape

(4349, 2)

In [14]:
df.head()

                                                text  label
0  New Delhi, 02 December. The threat of cyclonic...    0.0
1                                                NaN    1.0
2  After 7,350 new cases of Covid-19 were reporte...    0.0
3  New Delhi: An Indian Air Force helicopter cras...    1.0
4                                                NaN    1.0

In [15]:
df.tail()

                                                   text  label
4344  Congress (UP Congress) will launch women's man...    1.0
4345  Eco-friendly fireworks in the Golden Temple, s...    0.0
4346                                                NaN    1.0
4347  Kisan Morcha agreed but Kisan Union did not po...    1.0
4348  Railway News: If you are a senior citizen and ...    0.0

In [18]:
df = df.dropna(subset=['text', 'label'])

In [19]:
df.head()

                                                text  label
0  New Delhi, 02 December. The threat of cyclonic...    0.0
2  After 7,350 new cases of Covid-19 were reporte...    0.0
3  New Delhi: An Indian Air Force helicopter cras...    1.0
6  Sonia Gandhi: The story of coming from Italy t...    1.0
8  Dec 09, 2021_x000D_\n,_x000D_\n1:47pm_x000D_\n...    0.0

In [20]:
df.tail()

                                                   text  label
4342  A special bench of Chief Justice NV Ramana, Ju...    1.0
4344  Congress (UP Congress) will launch women's man...    1.0
4345  Eco-friendly fireworks in the Golden Temple, s...    0.0
4347  Kisan Morcha agreed but Kisan Union did not po...    1.0
4348  Railway News: If you are a senior citizen and ...    0.0

In [22]:
df.shape

(2695, 2)

In [23]:
df.duplicated().sum()

np.int64(34)

In [24]:
df.drop_duplicates(inplace=True)

In [26]:
df.shape # final dataset shape

(2661, 2)

In [27]:
import re

def clean_text(text):

    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text)

    return text

In [28]:
df["text"] = df["text"].apply(clean_text)

In [29]:
print(df["label"].value_counts())

label
1.0    1352
0.0    1309
Name: count, dtype: int64

In [30]:
df.to_csv("final_preprocessed_dataset.csv", index=False)